# Generated by Django 3.2.4 on 2021-08-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('teams', '0003_auto_20210813_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='truck',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_driver', to='core.truck'),
        ),
        migrations.AddField(
            model_name='member',
            name='truck',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='core.truck'),
        ),
    ]
