# Generated by Django 3.2.4 on 2021-09-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210826_0721'),
        ('teams', '0006_remove_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.fleet'),
        ),
        migrations.AddField(
            model_name='member',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.fleet'),
        ),
    ]
