# Generated by Django 3.2.4 on 2021-09-08 13:23

from django.db import migrations
from django.db.models import F

def forward( apps, schema_editor):
    Member = apps.get_model('teams', 'Member')
    Invitation = apps.get_model('teams', 'Invitation')

    for o in Member.objects.all():
        o.company_id = o.team.fleet_id
        o.save()
    for o in Invitation.objects.all():
        o.company_id = o.team.fleet_id
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20210908_1323'),
    ]

    operations = [
        migrations.RunPython( forward, lambda *a,**ka: None),
    ]
