# Generated by Django 3.2.4 on 2021-09-08 13:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210826_0721'),
        ('teams', '0008_auto_20210908_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'company')},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
