# Generated by Django 3.2.4 on 2021-09-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20210908_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='invitation',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
