# Generated by Django 3.2.4 on 2021-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20210915_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('DRIVER', 'DRIVER'), ('MEMBER', 'MEMBER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('DRIVER', 'DRIVER'), ('MEMBER', 'MEMBER')], max_length=20),
        ),
    ]
