# Generated by Django 3.2.4 on 2021-09-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_rename_role_driver2member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('MEMBER', 'MEMBER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('OWNER', 'OWNER'), ('MEMBER', 'MEMBER')], max_length=20),
        ),
    ]
