# Generated by Django 3.2.4 on 2021-09-15 12:24

from django.db import migrations


def forward( apps, schema_editor):
    User = apps.get_model('users', 'User')
    for u in User.objects.all():
        u.name = (u.first_name + ' ' + u.last_name).strip()
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.RunPython( forward, lambda *a,**ka: None),
    ]
