# Generated by Django 3.2.4 on 2021-08-13 10:55

import core.models
from django.db import migrations, models
import django.db.models.deletion
import lib.models
import lib.usphones


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vmrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('zip_code', lib.models.ZipCodeField(blank=True, default='', max_length=10)),
                ('state', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AS', 'AS'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('GU', 'GU'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('MP', 'MP'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('phone', lib.usphones.PhoneNumberField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', core.models.EasyURLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.company_logo_upload_to)),
            ],
            options={
                'abstract': False,
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=70)),
                ('vin', models.CharField(blank=True, max_length=17, null=True)),
                ('registration_plate', models.CharField(blank=True, default='', max_length=20)),
                ('registration_state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AS', 'AS'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('GU', 'GU'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('MP', 'MP'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default='', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=70)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('engine_model', models.CharField(blank=True, default='', max_length=70)),
                ('engine_hp', models.IntegerField(blank=True, null=True)),
                ('transmission_model', models.CharField(blank=True, default='', max_length=70)),
                ('transmission_gears', models.CharField(blank=True, default='', max_length=70)),
                ('color', models.CharField(blank=True, default='', max_length=70)),
                ('tire_size', models.CharField(blank=True, default='', max_length=70)),
                ('status', models.CharField(choices=[('IN_SERVICE', 'IN_SERVICE'), ('OUT_OF_SERVICE', 'OUT_OF_SERVICE')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.truck_photo_upload_to)),
                ('engine_vmrs_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_34')),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='core.fleet')),
                ('transmission_vmrs_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_34')),
                ('vmrs_equipment_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='vmrs.vmrs_codekey_2')),
                ('vmrs_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='vmrs.vmrs_codekey_34')),
            ],
            options={
                'unique_together': {('unit_number', 'fleet'), ('vin', 'fleet')},
            },
        ),
        migrations.CreateModel(
            name='Repairshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('zip_code', lib.models.ZipCodeField(blank=True, default='', max_length=10)),
                ('state', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AS', 'AS'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('GU', 'GU'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('MP', 'MP'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('VI', 'VI'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('phone', lib.usphones.PhoneNumberField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', core.models.EasyURLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.models.company_logo_upload_to)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_vendors', to='core.fleet')),
                ('verified_repairshop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_clones', to='core.repairshop')),
            ],
            options={
                'unique_together': {('name', 'state', 'namespace')},
            },
        ),
    ]
