# Generated by Django 3.2.4 on 2021-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='_unit_number_lower',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
