# Generated by Django 3.2.4 on 2021-08-20 11:19

from django.db import migrations


def forward( apps, schema_editor):
    Truck = apps.get_model('core', 'Truck')
    for t in Truck.objects.all():
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_truck__unit_number_lower'),
    ]

    operations = [
        migrations.RunPython( forward, lambda *a,**ka: None),
    ]
