# Generated by Django 3.2.4 on 2021-08-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210820_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='_vin_lower',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='truck',
            unique_together={('_unit_number_lower', 'fleet'), ('_vin_lower', 'fleet')},
        ),
    ]
