# Generated by Django 3.2.4 on 2021-08-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMRS_CodeKey_16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('meaning', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VMRS_CodeKey_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('meaning', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VMRS_CodeKey_34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('meaning', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('obsolete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VMRS_CodeKey_33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11, unique=True)),
                ('meaning', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('obsolete', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_33')),
                ('supergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_33')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_33')),
            ],
            options={
                'verbose_name': 'CK33 Component Codes',
                'verbose_name_plural': 'CK33 Component Codes',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
