# Generated by Django 3.2.4 on 2021-08-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210826_0721'),
        ('vmrs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VMRS_CodeKey_16',
            new_name='CodeKey16',
        ),
        migrations.RenameModel(
            old_name='VMRS_CodeKey_2',
            new_name='CodeKey2',
        ),
        migrations.RenameModel(
            old_name='VMRS_CodeKey_33',
            new_name='CodeKey33',
        ),
        migrations.RenameModel(
            old_name='VMRS_CodeKey_34',
            new_name='CodeKey34',
        ),
        migrations.AlterModelOptions(
            name='codekey33',
            options={'ordering': ['pk'], 'verbose_name': 'CK33 Component Code'},
        ),
    ]
