# Generated by Django 3.2.4 on 2021-08-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmrs', '0002_auto_20210831_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codekey16',
            options={'ordering': ['pk'], 'verbose_name': 'CK16 Repair Priority Class', 'verbose_name_plural': 'CK16 Repair Priority Classes'},
        ),
        migrations.AlterModelOptions(
            name='codekey2',
            options={'ordering': ['pk'], 'verbose_name': 'CK2 Equipment Category', 'verbose_name_plural': 'CK2 Equipment Categories'},
        ),
        migrations.AlterModelOptions(
            name='codekey34',
            options={'ordering': ['pk'], 'verbose_name': 'CK34 Manufacturer'},
        ),
    ]
