# Generated by Django 3.2.4 on 2021-08-13 10:55

from django.db import migrations, models
import django.db.models.deletion
import service_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vmrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('hourage', models.IntegerField()),
                ('service_start', models.DateTimeField(blank=True, null=True)),
                ('service_end', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=service_history.models.service_line_upload_to)),
                ('repairshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='core.repairshop')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='core.truck')),
                ('vmrs_repair_priority_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_16')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('PART', 'PART'), ('LABOR', 'LABOR'), ('SERVICE', 'SERVICE'), ('FEE', 'FEE')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('service_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_history.servicelog')),
                ('vmrs_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='vmrs.vmrs_codekey_33')),
            ],
        ),
    ]
